apiVersion: v1
kind: Service
metadata:
  name: {{ template "mosquitto.fullname" . }}-headless
  labels:
    app: {{ template "mosquitto.name" . }}
    chart: {{ template "mosquitto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.service.ports }}
  {{- if $value.enabled }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "mosquitto.name" . }}
    release: {{ .Release.Name }}
