apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snapshotpolicies.snapshotpolicy.ciscosso.io
spec:
  group: snapshotpolicy.ciscosso.io
  version: v1alpha1
  names:
    kind: SnapshotPolicy
    plural: snapshotpolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            claims:
              type: array
              nullable: true
              items:
                type: string
            selectors:
              type: array
              nullable: true
              items:
                type: object
            unit:
              type: string
              enum:
              - "day"
              - "hour"
              - "minute"
            period:
              type: integer
              minimum: 1
            retention:
              type: integer
              minimum: 1
            strategy:
              properties:
                name:
                  type: string
                  enum:
                  - "inuse"
