{{- if or .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "snapshotpolicy.serviceAccountName" . }}
  labels:
    app: {{ template "snapshotpolicy.name" . }}
    chart: {{ template "snapshotpolicy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}