apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "volumesnapshot.fullname" . }}-controller
  labels:
    app: {{ template "volumesnapshot.name" . }}
    chart: {{ template "volumesnapshot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ template "volumesnapshot.name" . }}-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "volumesnapshot.name" . }}-controller
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "volumesnapshot.serviceAccountName" . }}
      containers:
        - name: snapshot-controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
          - --cloudprovider 
          - {{ .Values.cloud.provider }} 
          - --cloudconfig
          - "/config/{{ template "volumesnapshot.secretname" . }}"
          volumeMounts:
          - name: cloudconfig
            mountPath: "/config"
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
    {{- with .Values.controller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: cloudconfig
        secret:
          secretName: {{ template "volumesnapshot.secretname" . }}
