{{- if .Values.cloud.secret.create }}
apiVersion: v1
data:
  {{ template "volumesnapshot.secretname" . }}: {{ include "volumesnapshot.cloudConfig" . | b64enc }}
kind: Secret
metadata:
  name: {{ template "volumesnapshot.secretname" . }}
type: Opaque
{{- end}}
