name: vernemq
home: https://github.com/erlio/vernemq
version: 0.1.0
appVersion: 1.5.0
description: VerneMQ is a distributed MQTT message broker based on Erlang/OTP.
icon: https://vernemq.com/images/wordtype@2x.png
sources:
- https://hub.docker.com/r/erlio/docker-vernemq/~/dockerfile/
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
maintainers:
- name: josdotso
  email: josdotso@cisco.com
