appVersion: 1.10.2
description: Chart for the nginx server
engine: gotpl
home: http://www.nginx.org
keywords:
- nginx
- http
- web
- www
- reverse proxy
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: nginx
sources:
- https://github.com/bitnami/bitnami-docker-nginx
version: 0.5.0
