name: oauth2-proxy
version: 0.6.0
# This chart is deprecated and no longer maintained as it's upstream has been abandoned.
# We keep & maintain it therefore in our cisco-sso repo
apiVersion: v1
appVersion: 2.2
home: http://www.videntity.com/
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
maintainers:
sources:
- https://github.com/bitly/oauth2_proxy
- https://github.com/cisco-sso/oauth2_proxy
engine: gotpl
